name: Accept Submission
description: Notify the user that a submission was accepted
body:
  - type: markdown
    attributes:
      value: |
        This is some description
  - type: input
    attributes:
      label: Researcher name
    validations:
      required: true
  - type: textarea
    attributes:
      label: Congratulations text
      description:
        Some words to congratulate the researcher about their findings.
    validations:
      required: true
  - type: dropdown
    id: deployment
    attributes:
      label: Select a template
      options:
        - Submission successful
        - More details required
        - Some other template
    validations:
      required: true
